import re
from datetime import datetime

# ✏️ UPDATED FROM PROFILE SCREENSHOT
USERNAME = "ayomiolutoye"
POINTS = 46  # Exact match from profile header
STREAK = 111  # Updated 111-day streak
RANK = "[0x9] MAGE"
RANK_POSITION = 90671  # Updated rank position!
TOP_PERCENT = "4%"

COMPLETED_ROOMS = [
    {"title": "How Websites Work", "url": "https://tryhackme.com/room/howwebsiteswork"},
    {"title": "Putting it all together", "url": "https://tryhackme.com/room/puttingitalltogether"},
    {"title": "DNS in Detail", "url": "https://tryhackme.com/room/dnsindetail"},
    {"title": "HTTP in Detail", "url": "https://tryhackme.com/room/httpindetail"},
    {"title": "What is Networking?", "url": "https://tryhackme.com/room/whatisnetworking"},
    {"title": "Intro to LAN", "url": "https://tryhackme.com/room/introtolan"},
    {"title": "OSI Model", "url": "https://tryhackme.com/room/osimodelzi"},
    {"title": "Packets & Frames", "url": "https://tryhackme.com/room/packetsframes"},
    {"title": "Extending Your Network", "url": "https://tryhackme.com/room/extendingyournetwork"},
    {"title": "Careers in Cyber", "url": "https://tryhackme.com/room/careersincyber"},
    {"title": "Virtualisation Basics", "url": "https://tryhackme.com/room/virtualisationbasics"},
    {"title": "Client-Server Basics", "url": "https://tryhackme.com/room/clientserverbasics"},
    {"title": "Inside a Computer System", "url": "https://tryhackme.com/room/insideacomputersystem"},
    {"title": "Offensive Security Intro", "url": "https://tryhackme.com/room/offensivesecurityintro"},
    {"title": "Computer Types", "url": "https://tryhackme.com/room/computertypes"},
    {"title": "Defensive Security Intro", "url": "https://tryhackme.com/room/defensivesecurityintro"},
    {"title": "Operating System Security", "url": "https://tryhackme.com/room/operatingsystemsecurity"},
    {"title": "Search Skills", "url": "https://tryhackme.com/room/searchskills"},
    {"title": "Operating Systems: Introduction", "url": "https://tryhackme.com/room/operatingsystemsintroduction"},
    {"title": "Search Skills", "url": "https://tryhackme.com/room/searchskillscS"},  # Distinct real completion, different slug on THM
    {"title": "Linux CLI Basics", "url": "https://tryhackme.com/room/linuxclibasics"},
    {"title": "Data Representation", "url": "https://tryhackme.com/room/datarepresentation"},
    {"title": "Data Encoding", "url": "https://tryhackme.com/room/dataencoding"},
    {"title": "JavaScript: Simple Demo", "url": "https://tryhackme.com/room/javascriptsimpledemo"},
    {"title": "Python: Simple Demo", "url": "https://tryhackme.com/room/pythonsimpledemo"},
    {"title": "Windows Basics", "url": "https://tryhackme.com/room/windowsbasics"},
    {"title": "Cloud Computing Fundamentals", "url": "https://tryhackme.com/room/cloudcomputingfundamentals"},
    {"title": "Windows CLI Basics", "url": "https://tryhackme.com/room/windowsclibasics"},
    {"title": "The CIA Triad", "url": "https://tryhackme.com/room/theciatriad"},
    {"title": "Database SQL Basics", "url": "https://tryhackme.com/room/databasesqlbasics"},
    {"title": "Cryptography Concepts", "url": "https://tryhackme.com/room/cryptographyconcepts"},
    {"title": "Become a Hacker", "url": "https://tryhackme.com/room/becomeahacker"},
    {"title": "Become a Defender", "url": "https://tryhackme.com/room/becomeadefender"},
    {"title": "Linux Fundamentals Part 1", "url": "https://tryhackme.com/room/linuxfundamentalspart1"},
    {"title": "Linux Fundamentals Part 2", "url": "https://tryhackme.com/room/linuxfundamentalspart2"},
    {"title": "Linux Fundamentals Part 3", "url": "https://tryhackme.com/room/linuxfundamentalspart3"},
    {"title": "Windows Fundamentals 1", "url": "https://tryhackme.com/room/windowsfundamentals1xbx"},
    {"title": "Windows Fundamentals 2", "url": "https://tryhackme.com/room/windowsfundamentals2x0x"},
    {"title": "Windows Fundamentals 3", "url": "https://tryhackme.com/room/windowsfundamentals3xzx"},
    {"title": "Wireshark: The Basics", "url": "https://tryhackme.com/room/wiresharkthebasics"},
    {"title": "Active Directory Basics", "url": "https://tryhackme.com/room/winadbasics"},
    {"title": "Windows Command Line", "url": "https://tryhackme.com/room/windowscommandline"},
    {"title": "Networking Concepts", "url": "https://tryhackme.com/room/networkingconcepts"},
    {"title": "Networking Essentials", "url": "https://tryhackme.com/room/networkingessentials"},
    {"title": "Networking Core Protocols", "url": "https://tryhackme.com/room/networkingcoreprotocols"},
    {"title": "Networking Secure Protocols", "url": "https://tryhackme.com/room/networkingsecureprotocols"},
    {"title": "Windows PowerShell", "url": "https://tryhackme.com/room/windowspowershell"},
    {"title": "Linux Shells", "url": "https://tryhackme.com/room/linuxshells"},
    {"title": "Blue", "url": "https://tryhackme.com/room/blue"},
    {"title": "John the Ripper: The Basics", "url": "https://tryhackme.com/room/johntheripperbasics"},
    {"title": "Metasploit: Exploitation", "url": "https://tryhackme.com/room/metasploitexploitation"},
    {"title": "Metasploit: Introduction", "url": "https://tryhackme.com/room/metasploitintro"},
    {"title": "Metasploit: Meterpreter", "url": "https://tryhackme.com/room/meterpreter"},
    {"title": "Moniker Link (CVE-2024-21413)", "url": "https://tryhackme.com/room/monikerlink"},
    {"title": "Nmap: The Basics", "url": "https://tryhackme.com/room/nmap"},
    {"title": "Tcpdump: The Basics", "url": "https://tryhackme.com/room/tcpdump"},
    {"title": "Public Key Cryptography Basics", "url": "https://tryhackme.com/room/publickeycrypto"},
    {"title": "Cryptography Basics", "url": "https://tryhackme.com/room/cryptographybasics"},
    {"title": "Hashing Basics", "url": "https://tryhackme.com/room/hashingbasics"},
    {"title": "JavaScript Essentials", "url": "https://tryhackme.com/room/javascriptessentials"},
    {"title": "Web Application Basics", "url": "https://tryhackme.com/room/webapplicationbasics"},
    {"title": "SQL Fundamentals", "url": "https://tryhackme.com/room/sqlfundamentals"},
    {"title": "Hydra", "url": "https://tryhackme.com/room/hydra"},
    {"title": "Burp Suite: The Basics", "url": "https://tryhackme.com/room/burpsuitebasics"},
    {"title": "Gobuster: The Basics", "url": "https://tryhackme.com/room/gobusterthebasics"},
    {"title": "SQLMap: The Basics", "url": "https://tryhackme.com/room/sqlmapthebasics"},
    {"title": "Shells Overview", "url": "https://tryhackme.com/room/shellsoverview"},
    {"title": "SOC Fundamentals", "url": "https://tryhackme.com/room/socfundamentals"},
    {"title": "Digital Forensics Fundamentals", "url": "https://tryhackme.com/room/digitalforensicsfundamentals"},
    {"title": "Incident Response Fundamentals", "url": "https://tryhackme.com/room/incidentresponsefundamentals"},
    {"title": "Logs Fundamentals", "url": "https://tryhackme.com/room/logsfundamentals"},
    {"title": "Junior Security Analyst Intro", "url": "https://tryhackme.com/room/jrsecanalystintrouxo"},
    {"title": "Splunk: The Basics", "url": "https://tryhackme.com/room/splunk101"},
    {"title": "Firewall Fundamentals", "url": "https://tryhackme.com/room/firewallfundamentals"},
    {"title": "IDS Fundamentals", "url": "https://tryhackme.com/room/idsfundamentals"},
    {"title": "Vulnerability Scanner Overview", "url": "https://tryhackme.com/room/vulnerabilityscanneroverview"},
    {"title": "Snort", "url": "https://tryhackme.com/room/snort"},
    {"title": "Snort Challenge - The Basics", "url": "https://tryhackme.com/room/snortchallenges1"},
    {"title": "Introduction to SIEM", "url": "https://tryhackme.com/room/introtosiem"},
    {"title": "CyberChef: The Basics", "url": "https://tryhackme.com/r/room/cyberchefbasics"},
    {"title": "CAPA: The Basics", "url": "https://tryhackme.com/r/room/capathebasics"},
]
